export enum PersonalityTypes {
  TRAIT_TYPE_INTROVERTED,
  TRAIT_TYPE_EXTRAVERTED,
  TRAIT_TYPE_SENSING,
  TRAIT_TYPE_INTUITIVE,
  TRAIT_TYPE_THINKING,
  TRAIT_TYPE_FEELING,
  TRAIT_TYPE_JUDGING,
  TRAIT_TYPE_PERCEIVING
}
